# Generated by Django 4.0.3 on 2022-04-07 00:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0003_rename_intro_profiles_bio_profiles_created_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profiles',
            name='member_type',
            field=models.CharField(choices=[('Instructor', 'Instructor'), ('Attendee', 'Attendee')], default='Choose Member Type', max_length=100),
        ),
    ]
