# Generated by Django 4.0.3 on 2022-03-31 22:36

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('register', '0003_member_details'),
    ]

    operations = [
        migrations.RenameField(
            model_name='member_details',
            old_name='register',
            new_name='full_name',
        ),
    ]
