# Generated by Django 4.0.3 on 2022-03-31 22:47

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('register', '0004_rename_register_member_details_full_name'),
    ]

    operations = [
        migrations.CreateModel(
            name='Workshop_details',
            fields=[
                ('workshop_name', models.CharField(max_length=2000)),
                ('workshop_details', models.TextField(null=True)),
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False, unique=True)),
            ],
        ),
        migrations.AddField(
            model_name='register',
            name='Workshop_details',
            field=models.ManyToManyField(blank=True, to='register.workshop_details'),
        ),
    ]
