# Generated by Django 4.0.3 on 2022-04-05 04:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('register', '0005_workshop_details_register_workshop_details'),
    ]

    operations = [
        migrations.AddField(
            model_name='register',
            name='profile_pic',
            field=models.ImageField(blank=True, default='default.jpg', null=True, upload_to=''),
        ),
    ]
