# Generated by Django 4.0.3 on 2022-04-06 04:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('register', '0006_register_profile_pic'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='member_details',
            name='full_name',
        ),
        migrations.AddField(
            model_name='register',
            name='Member_details',
            field=models.ManyToManyField(blank=True, null=True, to='register.member_details'),
        ),
    ]
