# Generated by Django 4.0.3 on 2022-03-31 22:33

from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('register', '0002_register_member_type'),
    ]

    operations = [
        migrations.CreateModel(
            name='Member_details',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False, unique=True)),
                ('skill_set', models.CharField(max_length=2000)),
                ('reason', models.TextField(null=True)),
                ('register', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='register.register')),
            ],
        ),
    ]
