# Generated by Django 4.0.3 on 2022-04-07 00:03

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0001_initial'),
        ('register', '0008_remove_register_member_details_register_reason_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='register',
            name='owner',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='users.profiles'),
        ),
    ]
