# Generated by Django 4.0.3 on 2022-04-10 02:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('register', '0009_register_owner'),
    ]

    operations = [
        migrations.AddField(
            model_name='workshop_details',
            name='workshop_date',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='workshop_details',
            name='workshop_subject',
            field=models.CharField(blank=True, max_length=5000, null=True),
        ),
        migrations.AddField(
            model_name='workshop_details',
            name='workshop_time',
            field=models.TimeField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='workshop_details',
            name='workshop_details',
            field=models.TextField(blank=True, null=True),
        ),
    ]
