# Generated by Django 4.0.3 on 2022-04-10 02:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('register', '0010_workshop_details_workshop_date_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='workshop_details',
            name='workshop_date',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
        migrations.AlterField(
            model_name='workshop_details',
            name='workshop_name',
            field=models.CharField(blank=True, max_length=2000, null=True),
        ),
        migrations.AlterField(
            model_name='workshop_details',
            name='workshop_time',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
    ]
