# Generated by Django 4.0.3 on 2022-04-10 02:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0004_alter_profiles_member_type'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profiles',
            name='member_type',
            field=models.CharField(choices=[('Select Member Type', 'Select Member Type'), ('Instructor', 'Instructor'), ('Attendee', 'Attendee')], default='', max_length=100),
        ),
    ]
